1.1enfinal

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -673,7 +673,7 @@ SCOLOR='\033[0m'
 				echo -e "\033[1;32mRESTART SSL TUNNEL!\n"
 				fun_bar 'service stunnel4 restart' '/etc/init.d/stunnel4 restart'
 				echo ""
-				netstat -nltp | grep 'stunnel4' >/dev/null && echo -e "\033[1;32mSUCCESSFULLY CHANGED PORT !" || echo -e "\033[1;31mERRO INESPERADO!"
+				netstat -nltp | grep 'stunnel4' >/dev/null && echo -e "\033[1;32mSUCCESSFULLY CHANGED PORT !" || echo -e "\033[1;31mUNEXPECTED ERROR!"
 				sleep 3.5s
 				clear
 				fun_conexao
@@ -705,7 +705,7 @@ SCOLOR='\033[0m'
 			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mINSTALL SSL TUNNEL WEBSOCKET\033[0m"
 			echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mBACK\033[0m"
 			echo ""
-			echo -ne "\033[1;32mRaj, pick a card \033[1;33m\033[1;37m "
+			echo -ne "\033[1;32mPlease pick an option \033[1;33m\033[1;37m "
 			read resposta
 			echo ""
             if [[ "$resposta" = '1' ]]; then
@@ -881,16 +881,16 @@ SCOLOR='\033[0m'
 				fi
 				echo -e "\E[44;1;37m          MANAGE OPENVPN           \E[0m"
 				echo ""
-				echo -e "\033[1;33mPORTA\033[1;37m: \033[1;32m$opnp"
+				echo -e "\033[1;33mPORT\033[1;37m: \033[1;32m$opnp"
 				echo ""
 				echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mCHANGE PORT"
 				echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mREMOVE OPENVPN"
 				echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mOVPN VIA LINK $ovpnweb"
 				echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;37m• \033[1;33mMULTILOGIN OVPN $mult"
 				echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mCHANGE HOST DNS"
-				echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mBACK"
+				echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mRETURN"
 				echo ""
-				echo -ne "\033[1;32mPick an Option \033[1;33m\033[1;31m?\033[1;37m "
+				echo -ne "\033[1;32mPlease pick an option \033[1;33m\033[1;31m?\033[1;37m "
 				read option
 				case $option in
 				1)
@@ -1112,9 +1112,9 @@ SCOLOR='\033[0m'
 					echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mADD DNS HOST"
 					echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mREMOVE HOST DNS"
 					echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mEDIT MANUALLY"
-					echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mBACK"
+					echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mRETURN"
 					echo ""
-					echo -ne "\033[1;32mRaj, pick a card \033[1;33m\033[1;31m?\033[1;37m "
+					echo -ne "\033[1;32mPlease pick an option \033[1;33m\033[1;31m?\033[1;37m "
 					read resp
 					[[ -z "$resp" ]] && {
 						echo ""
@@ -1287,9 +1287,9 @@ SCOLOR='\033[0m'
 			# Adquirindo easy-rsa
 			echo ""
 			fun_dep() {
-				wget -O ~/EasyRSA-3.0.1.tgz "https://github.com/leitura/SSHPLUS/raw/master/Install/EasyRSA-3.0.1.tgz"
+				wget -O ~/EasyRSA-3.0.1.tgz "https://github.com/tblesshack/SSHPlus/raw/master/Install/EasyRSA-3.0.1.tgz"
 				[[ ! -e $HOME/EasyRSA-3.0.1.tgz ]] && {
-					wget -O ~/EasyRSA-3.0.1.tgz "https://github.com/leitura/SSHPLUS/raw/master/Install/EasyRSA-3.0.1.tgz"
+					wget -O ~/EasyRSA-3.0.1.tgz "https://github.com/tblesshack/SSHPlus/raw/master/Install/EasyRSA-3.0.1.tgz"
 				}
 				tar xzf ~/EasyRSA-3.0.1.tgz -C ~/
 				mv ~/EasyRSA-3.0.1/ /etc/openvpn/
@@ -1460,7 +1460,7 @@ exit 0' >$RCLOCAL
 			EOF
 			# gerar client.ovpn
 			newclient "SSHPLUS"
-			[[ "$(netstat -nplt | grep -wc 'openvpn')" != '0' ]] && echo -e "\n\033[1;32mOPENVPN INSTALLED SUCCESSFULLY\033[0m" || echo -e "\n\033[1;31mERRO ! A INSTALACAO CORROMPEU\033[0m"
+			[[ "$(netstat -nplt | grep -wc 'openvpn')" != '0' ]] && echo -e "\n\033[1;32mOPENVPN INSTALLED SUCCESSFULLY\033[0m" || echo -e "\n\033[1;31mERROR ! THE INSTALLATION IS CORRUPTED\033[0m"
 		}
 		sed -i '$ i\echo 1 > /proc/sys/net/ipv4/ip_forward' /etc/rc.local
 		sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.local
@@ -1494,7 +1494,7 @@ exit 0' >$RCLOCAL
 		echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;37m• \033[1;33mOPEN PORT\033[0m"
 		echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mCHANGE SSH SOCKS STATUS\033[0m"
         echo -e "\033[1;31m[\033[1;36m6\033[1;31m] \033[1;37m• \033[1;33mCHANGE WEBSOCKET STATUS\033[0m"
-		echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mBACK\033[0m"
+		echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mRETURN\033[0m"
 		echo ""
 		echo -ne "\033[1;32mRaj, pick a card \033[1;33m\033[1;37m "
 		read resposta
